"use client"
import Image from 'next/image'
import Link from 'next/link'
import React, { useEffect } from 'react';
import { Card, Col, Container, Form, Row } from 'react-bootstrap'
import { useForm } from 'react-hook-form'
import "./style/insta.css"
import { useRouter } from 'next/navigation'
import axios from 'axios';
import { setCookie } from 'cookies-next';

export const metadata = {
    title: 'Login. instagram',
    description: 'Generated by Login. instagram',
}
const Front = () => {
    const { register, handleSubmit } = useForm();
const router = useRouter();

    const onSubmit = (data) => {
        axios.post("http://localhost:8080/api/userlogin",data)
            .then((res) => {
                // console.log(res.data)
                if(res.data.status === "success"){
                    localStorage.setItem("user",JSON.stringify(res.data.message))
                    setCookie("logged", "true");
                    router.push("/home")
                }
            }).catch((error) => {
                console.log(error)
            })

        // console.log(data);
    }
    useEffect(() => {
        const loader = document.getElementById('loader');
        if (loader) {
          loader.style.display = 'none';
        }
      }, []);
    return (
        <>
        <div id="loader">
        <div class="camera-icon">
            <img src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBw8PDxAQDQ8QEA8SEA8PEA8QDw8NDxYVGBIWFxUVFhcYHSkgGBolGxUVITEhJSkrLi4uFx8zODMsNygtLisBCgoKDg0OGhAQFy0lHyAtLS0rLi0tLS0vNy0tLS0tLS0tKy0tLS0vLS8tLS0tLS0rLS0tKy0tLS0tLS0rLS0tK//AABEIAOEA4QMBIgACEQEDEQH/xAAcAAABBAMBAAAAAAAAAAAAAAAAAQUGBwIDBAj/xABMEAABAwIACQYGDggHAQAAAAABAAIDBBEFBgcSITFBUXETImGBkaEyUpKxwdIUFyM0QlNiY3J0orPC0RYzVIKTo8PhJENkhLLi8PH/xAAbAQABBQEBAAAAAAAAAAAAAAAGAQIDBAUAB//EAD8RAAECAwIJCAgGAgMAAAAAAAEAAgMEEQUxEiFBUXGRobHRBhMyUmGBwfAUFSIjNEKCskNTcqLS4TOSNWLx/9oADAMBAAIRAxEAPwC8UIXHhHCEVNE+ad4ZGwXLj3AbyToA2pQCTQDGuGPEuom2k6lDMPZRqOmuyEmpkGj3Mjkgel+390FQHHHHeaucY4s6KlvYRg5rnjfIRr+jqHTrUSsimRsBtA+ZOPqjxPgNa0IUllfq48FMcJ5SsITX5NzIG6dETLut0uffusmKbGKuffPrKh19NjNNbsvYJrASgLdhysCEKMYB3Dfer0OA0XNGpbXTPdpc9xO8uJPesbneUAJQFIaBXGsKAsggBZAKMlWGsQEoSgLIBRkqw1qAlAQAsgFGSrDWIASgLIBKAoyVYaxIAlASgJQFGSp2sSgLK53pEJilolDzvPaVujrJW+C9w4OcFoQkIBvCTBGZOUWMFY3wamYDomkA86daDH2uiPPc2VtvBkbnHtFj3qLoUT4EFwo5g1KGJKQIgo+G09w337Va2B8fqaazZwYHnRnXDor+dvWLdKl0MrXtDmODmkXa5pDmkbwRrXntP2LeNU9G7Qc+InnROJtxbuNto67rLmLMbSsLUeOTv1ofn+TrCC6WND1Td3E4x310hXWhN+CcJxVUQlhN2nQQdD2u2tcNhTgsYgg0KEnscxxa4UIvCEIQkTViTbSdSpDKBjSa2bk43H2NE4hgGp7tIMh77bhxKn+U7DPsajMbDaSe8ejWGW5569Df3lS6J7CkwB6Q6+5vifAd617OlajnT3eJ8Na12S2WdkuaiPDWqISwASgLOyUNTC9SiEsQFkAsg1bIoHusGMc5x1BoLieACYXKdsNagFkApBSYmYRk8Gle0fOARdzyCnKLJzXnWIm9DpGnzAqnEnYDb4g1hNMxLs6URusKHgJQFOhkxq/jqcfvSeolGTKq2zU/lSH8CgdaMt+YE9s/KZYoUGASgKdjJlU/HQeVJ6qUZM6n46DypPVUZtCX6428FK20pL80beCgoCyAU69rWo+Ng8qT1Ee1rU/GweVL6qYbQl+uNvBTC1JEfjDbwUHQpt7WtVsmg8qQfgQcm1V8bT+XJ6iT06X64TxaskfxQoSkUvlyeVo8ExO4SfmAm6qxNwhGCXU7nj5BEp6g0k9ycJuA6541qRloSr8TYrf9gmFC21VHLE4tljc0j4LmOa7sK0qTDVwY8aEISJpclSoSITcJcnvFXD76GZrhd0brNlZfQRcabb9oP5lXTTzMkY2SNwcx7Q9rhqIIuCvPas3JdhcvjfTPNzH7oz6JIzm9RIP7xWXaELCbzgvF/nzi0Ia5Q2eHwvSWD2m39ou2buwBT5CELIQYqYyoVxmr8z4MLGRjdfS5x+3b91Q+yd8Z5M+tqXXuHVEpbwznAd1k25qO5YCHBYwZANyNpaBgwWtGYblrzUuatlkWUuErIgrABbqenc9zWRhznONmtaC5xO4Aa1lT07pXNYxpLi4Na0aSSTYAK5MUMVo6Fgc8B1QRzna83e1p852qlOTzZZlTjJuHnIqs7NQ5RlTjJuGfTmG9R/F3JwAA/CBN9B5Bj7jg5w2a9De1TugwbBTttTxRxDbmNAJ4nWetdq0zStY0ue4NaBcucQ0AdJKFZibjRz7x3dk1ITmJyNHPtu7smpbkKO1+ONDDcGUyOGtsQzz1O0NPamybKNS/Aimd9LMZ6SkbKR3YwwqWHZk5EFWwjTRTepqhQB+UyP4NM88ZQ38JWHtnt/ZHfxh6ilFnTJ+TaOKsCw58/h/ubxVhIVe+2e39kd/GHqI9s9v7I7+MPUXerpnqbW8UvqKf/L/cz+SsJCr32zmfsjv4w9RHtnt/ZHfxh6i71dM9XaOK71FP/l/uZ/JWEhV57Z7f2R38Yeos2ZTY/hUzhwlDvwhIZCYHy7RxSGw58fh/ubxVgIUHjyk0vw4pRwMbvOQnCkx5wfLYGR0ROgCRlu9twFE6VjC9hUL7KnWCpgu7hXdVSCqpY5Rmyxskb4r2iQd6hmHsn8MgL6Q8m/SeTeTyR4HW3vHBTSnqWSNDo3tkadTmOD29oW9MhxXwz7Jp5zKKWnZiVd7txGcZO8XLz7hCglp3ujma5jxscO8bx0hcyvDGLAEVbFmPAEgB5OQAXB3H5O8KmMJ4PkppXxStzXNNrbOgjeCNK2ZeaEYZiPOJHNl2oydZSlHi8eI7N208qFihTYS1qLJPeJlaYK6B19DntjduzXnNdfhe/UmJZxEh7SNBBBB2pj6OaWnKmRYQisMM3OBGsUXotCZf0gj3d4Qh+hXmHokbqqkq450r3b3OPa4rnst0g53WfOksjgOoF6IyDQALCyLLZZbKeLOexoFyXNaBvJNgEmEpRDzqwcmGAs0GskBziXMiuNOwOd+HylYi48F0bYIY4m6mMay9rXIGk9Zuetb5pQxrnONmtBc4nUABclB8zHMeKXnu0ZF5zPTRmY7omTJoycdJKa8YcORUUWfIc57riOMEZzjb/jvKqXDeMNRWPJle7NvdrGFzWD6Lb7tp09KTGbC76yofI4nNzsxjDsaHHNb6T0kprW/JSQgNDnD2t3YPNaozsuy2SjA5wrEN5zdgzUz5dCChCFeWwhCELlyEISJCVyEISJjnJUJEIUTnJUIT5ipi++vlzRzY2AOkfa9gdQHyjp7DuVkwYkYOa0NMJebWL3veHHySB2BUo02yGcE39iy522JaUdgRKl2YAGmmpHFVNgzDE9K8Phke0i1wDzXdB2EcVbOKeM8dcyxsydou5mxw0c5l9nRs71EMc8S20zDPSlxiBAkY7nObc6HA20i9hvHTsiGC619PKyWI5r2Pa4HZr0g9BFwegqCI2HMtwm35/AqCYlpe1pfnIR9rIctRkd2f+jLX0IoZlHwGJ6fl2D3WEXNtboxckath08M5SbBdayohjmZ4MjA62g2O1p6QbjqXTJGHAtcAWkEEHUQdYWWxxY6oyILl48SUjiIL2nGNhG9edLIXfh6h9jVM0OmzJHAE6CRnaD16D1pvWwH1xheoMcHtDmnEcY70qUbFilC7CT1JfZfykLg5VCq0WXzIXA7WeJQkukRAXgK+lT7iPTcpX07djXiTyAXfhCYVLsmMYNdfxY5XDuHpVaZi0hO0FVZ9+BKxHDI07lbijuPVdyNBMQbOfaIH6XhDyQ5SJQnKnLakjbtM2d2RuH4kOywBitrnCAbLhiJOQmm6o2Y/BVZdCxSol51ekpUJELudXJUBdeCsGS1UgjgYXOO3UANridgVm4v4i00ADqgCeXXZ1jE06NQtztuvsChjTrIQ9q/Ms+etOBJj3hx5AL/6HkVVaUOCKmc+4wvfptdrHuaOOwdaeoMQsIO8KNjeMjPQSrejjDQA0AAaAALAcAtizn2rEPRaBrP9bENxeUsYn3cNo01J8BsVPy5P68eCxjuEjL95CZq/AFZBczQStaNGdmuLfKAt3q+UJjbTifMAdY8UkLlLHHTY0jsqD4jYvOpBGtYq5cN4mUlUCWsEEnjRtaGk/KZqPVY9Kq/D2AZ6KTNmaS0+C9ucWOHQ70a1dhTbIuIYjmRHIWtLzmJmJ3VN/dn39in2SrM9iygW5Tlhn77cmM3qvn96nKovFfGB9BLntGcxwzZGE2BHoI2HjvVlw4+YPc3OMj2HxHsdnfZuO9ZszAfzhcBUFDds2ZMmZdFhsLg7HiFSOwjyE74wW9h1Wdq9jzX8gqhH6zxKmeOeOoqmchTNc2EkF7nWDnW0gWB0N1HedGpQpTSzCxprlW7YElFloDudFC41pmoKayrayW1ofSSRE3dHLq3Nc0EDtD1NVWWSOTn1Ld7WO8kkfiVmqnHFIhQtbkMMn4gGWh1gE7VUOVKmDK7PH+bDG88RdnmYFDFYWV1lpKZ29j29hJ9Kr1WoLvdhGtjvw5GEeymokeCVASIT8JaS7c5ItaFHUKtgJEiEi03RFIlU2yT++5fq7/vI1B7qcZJR/ipT/p3feRqpNRKwnDzeFRtX4KL+lWqq/wArj7RUw3vlPY1v5qwFXWV882k4z+aNZ0uaRQfNyC7DFZ+H9X2lVvdKsULT51eiUWV124IwbJVTMiiF3OdY7gNpduAC4FbmTrAYgphO8ESzDOF9bYzaw69fk7kyLMYDai9Z1pzok4BiXk4mjt4C/ZlT5gLA0VFCI4xpNi95ADnutrPRuGxOyFFcccaW0LcyOz6hwuAdLWDxndO4f+OXjee0oAhw487HoPae7zU9ifcIYRhp251RKyNum2cQCeA1k8FG5soVC02aJpPlNawN73A9yqutr5p3l80jnvOslxJ4DcOgaFzK42WZT2iiuW5NQGj3zi49mIbqnZoVuR5RqE2DmTt6c2MgcbOv3KQ4OwxTVIvTyskOvNvZ44tOkdioJbKaofG4Pjc5jmnObZxaQd4I1JXSzCPZNE6Y5NSz2+6cWnWNV+3uK9FLiwlg+KpidFM3OY7hcHY5p2EXUTxHxyFTanqiBOPAk0ASatB3O8/HXOVTc0sNDehOZlo0lGwX4nDGCNhBVE4zYDfQzOjfpYedG+2hzdh6CNVv7JmV3Y44EFZSuaB7qy8kRGvOA0t6xo42OxUk9tiQdi0oMfnG47wjux5/0yBhO6bcTvA9++uRIkQhPJWsp5kkd/iphvgceySP81aiqjJJ76l+ryfeRq11mRz7w924IA5Rik8dDdyrjLAObSHpn80arRWblhHudJ9ObzMVYqWGfYCKrB/4+H9X3OSoSITsJbC6ELC6E3CUVEISIUzoqVKp1kl99S/V3feRqCKdZJffU31d33jFXixatos61/gYujxCtVVzlf8ABpOM/wDTVjKuMsGqk41H9JQA0NUG2D/yEP6vtcq3QkQpeeXoi7sB0ZqKmGLTz5WNJGsAusT1C56lf0cYaA1os0AAAagBqCpvJrDnYSicNTGTO+wQO8hXQo3PwkE8qIhMdkPIG17yeAC4sKVraeCSZ2qNjn7rnY3iTYdaoXCVY+eV8shznvc51+km9huA1AbgrWyoVBZQWB0PmY13ANe7ztaqgTobw2q0OTMs1sB0Y3uNO4cTuCVCRCmEVEyW6EiE8RFyzikLCHNJaQQQQbEEaiDsKvPFXCvsukjlNuUtmSW8duvt0HrVEqyskdUSypicdAcyRo4gh3mb2JkY1boQ/wAopZr5TnMrCKaCQCNx7lYyo7Hug5CvmaBZjjyrdFhZ+k26ASR1K8VVmVyP/EwO3whvY959KjgOo/SsPk3FLZss6zTsx+BUCSJUiuYSPVOsknvuX6s/7yNWuqnyR++5vqzvvI1bCoRemUAco/jfpCrzLB+qpfpTeZqq9Whlg/VUv0pfM1Vcns6KKLA+Ah/V9xQhCFxWys7oWN0LklFmhCFWdGTUKdZJPfU31d33jFBg1TrJKLVUv1d33kah52rgFnWv8DF0eIVqquMsPg0n+4/pKx1XWV0XFH/uP6SkjOwWVQXYPx8P6vtcq0Qt2YjMVPn16JhBSTJnJm4Rjb47JW/YJ9CuZULi9Vinq4JToDJGFxGvNvZ/2SVfKsy8QPqgnlNDpHZEFxbTvB4EKGZU470Dbam1DC7oGZIL9tlUav8Aw7g8VNNNAbc9hDb6g7Ww9TgCqGqaVzHuY9pDmuc1zToIINiO1LEfgO0rT5NTLXSxhZWnYbttRqWlCXNSJBFRKhCEKZsRckVkZIYTapfbR7k0Hp5xPmHaq5DSSANqvDEvBJpKNkbhZ7vdZBp0OcBzdOqzQ0cbp+HUUWDyijthyZYb3kAdxBO4DvT+qryuyA1FO3dFndrnAeYq1FSeUOv5avlAN2xkQgH5Gv7ZKVnSCH+TcIunMPqtJ14vHeo0hCFZBR8pzkk9+S/Vn/eRq2FU+ST35L9Wf95GrYVaJ0ygDlH8b9IVeZYP1VL9KbzNVXq0MsH6ql+lN5mqsFNCHsoosD4CH9X3FYoWSE7BWykshZ2QlwU2qyDFmGLa1izDENPjqEvWoMU3yVC1VL9Xd95GogGKZ5MW2q5Omnef5kaZAjYUVo7fArNtR1ZOL+lWaq/ysNuKTjP5o1YCguVCO7KY7nyjtDfyWlPGkBx0bwg+xHYM9DP6vtKrfMS5i6MxGYh7n0d4a58xW1iLhUVFI1jj7rCGxuB1loHMd2C3FpVW5i7sC4SfSTtlj0gc17b2BYdbT2doCsS05zcSpuyrPtOV9LgFnzDG3Tm799CrrUIx5xS9k3qKYe72HKM0DPAB0j5YGjpFtylWDq+OpjbLC67TwuDta4bCF2ogc1sRvYUEy8xGk42G3E4YiDtBC88SwkEhwLSDYhwLSDtBB0grWWK9MMYv0tWPd4hn2/Ws5snbtHQbhRaqyaxknkalzR4r4w/vBHmVF0CK27H5zFGEtyhlYg95Vh0EjuI4BViWJA03sBdWVDkyH+ZVm25kIHeXHzKTYHxUo6Qh0cee8apJbSPHS3YDfaAFNDZEN4pq8FJH5RSkMVYS85gCNpA2AqKYh4mOaW1NYy1rOiic2xJ2PeDqtsGvaemykLnqqhkLHSSvDGNF3OJsAFbAoEGzk5FnIuG/QAMnYPNSU3Yz4XbR0sk2jPALIhvkIOb1DST0AqiXuJcSSSSbknSSdpKfscsYzXzHNu2Bl2xtO6+lzvlG3ULdbAuD6o4sSzjJwPb6bqE9mYd2XtqhIlSKZrlsqc5JPfc31d/3kathVTkjb/ipj/p3j+ZH+StZRu6RXn/KP40/pbuVdZYT7nSfTm8zFWSsvLD4NH9KfzRqtVag9FFNg4rPh/V9zkiEqFNgrXWdkqzzUJMFRVXWGLYGLMNW0NXn74tSqhctQYpTk6Nq3jFI3/ifQo4Gp7xQl5OugJ1FxZ5TS0d5CdKxKR2E5wqU77UvEaOqdytdQ/KPHenhdumt2sJ9CmCj+O1NylE+2kxubIB15p7nFEs60ul3gZkGWa8Mm4ZOemvEqtzUuYugMSiNBxcjkvXNyaXk11CNLyaTDTecW3A+FJqR+dE7QbZ8ZuWOHSN/SrEwPjHBVAAHk5NsTyAb/JOp3n6FW3JpeTVyWtKJAxDG3MfOLziWfOSMGaxuxOzjxz7+2iuRCq2iw5VwWDJXFo+C+z28BnauqydGY7VI1xQngHg/8itqHbEu7pVHdwWFEsWOD7JB76b+KnyFAJceKj4MUPXnn0hNFfjRWy3HLGNu6IcnbrHO7091rS/y1PdxSw7EmHH2i0DTXcFPsNYwU1G08s+77XETLOlPVsHSbBVTjRjRPXGxPJwNN2RNJI285x+E63UNg380sdySdJOknWSVzPiUHp5idgRLZ1ly8ocPpPznJoGTTjPam8hIuiSJaHNsrcOLVbwNUJEJVbY5OVgZIY/dal25jW9rgfQrQUDyT0eZTTy/GShvEMYNI63kdSnifWq85t14fPxKZKDUADtVY5XX8+lbua89rgPQq9U0yrVAfWNY0/q4Y2uG4kud5nBQpW4PRRnYzCyRhA5q6yT4pUBIlVtoWkujNSrLNQuooKpzDVsDVsLLEhKGrzF5oaLPLkgatkDyxzXt8JrmubxBuPMlDVkGqLCooy5W5TTiSNkjfBe1rxwIulnia9jmPF2uaWOHQRYqNYkYRzmGB55zLvZ0tJ0jqJ7+hStG0tGbHhB4y36coQLMwTAiuZmOLRkKqevoXQSvifrabX3jY4cQtIYrGw7gdtU0EWbI0c12y3iu6FB6mjfE4slaWuGw+cHaEJWhJvln1+Q3HwPbv1gE0nPiYZ/2F48R2bt/GGLLMW4MWeYs0vVvDXNyaMxdOYjMXYSTDXIY1gY12FixLEuGl5xcZjWp0a7ixa3MTw9SNiJvfGtD4k5OYtL41ZhxaKdsRNckS5JYk7SRrmkjWnAjq3DiJpcyyzpKd0kjY2NJc5zWgDSSSbALsjonyODI2Oc4mzWtBeT1BWfiVii2jaJpwHVLhaws5sYI0hpt4WwnqG0nZl3l9yin7ThykLDd0j0RnPDOc11VIMB4PbS00MDbe5sAcRtcdLz1uJKcL2SqJ5QsNimpXRtPus7TG22sNI5zuw2HSehXV5/BhRJuOGDG55v04yTvKq/GbCHsmrnm1hz3ZlxY5gNmdwCa0pKRW4dy9RYxrGhrbgABoGJKlCRKFbYnJy5NIuv2OhJhLN50J3wtDm1Ew8WWUdjytDWp6xvpOTq3nZIBIOsWPeCmprV5lNtLIz2nITv4LOgxechNdnA3LANWwNWbWrY1qqFyUuS0cjo3tfGbOabgqwsE4TZUsuNDx4bNoO8bwoC1q30sr43B8bi1w1Ef+0hXJC0nSrzUVabx4jt3rNnZVsw3MRcfA9m5WStFTTMkGbIxrhuIv/8AE04Nw+x9mze5v3/AP5daemOBALSCDqI0hGEGYhTLaw3AjzeEORIUSC6jhQ+bimSoxYgdpY57Oi4eO/T3rkdiodkwPGO3pUpQqz7Kk3mphgaKt2AgKZs/MN+fXQ7womcVpNkkfY4LE4rS+PH2v/JS5Ci9SSfVOs8VJ6ymM41KIfotN48fa/1UhxVm8ePtf6qmCEnqST6p/wBil9Zx841KGnFSbx4u1/qrE4pT+PF2v9VTRCX1LJ9U/wCxS+tJjONShJxPn+Mi7X+qsTiVKdcsQ8s+hThCcLHlB8p1nil9bTOcagoO3EVx8OoaODC70hdNNiJTixlkkkPRmxt9J71L0KZlnSzLmayTvKQ2tOEU5ymgAbguCgwXBTi0ETGXGkgc48XHSesrvSE207FGMN4409OCIiJ5dgYQY7/Kfq6hfqVlz2Qm46Aebgq0KDHmohwAXON/9k7ynXDWF4qOIyzHRpzWg89ztjWj/wBZUlh/C0tbM+aXWb5jdJa1o8EDcB3kk7V0YdwrPVymSd99jWjQxo3NGwd523TS5qayMHFHNkWUyTaXONXm85AMw8Tl0LFCEK/DK20q2RC7hxC1hO+KVEZ62CPNzm8o1zx8lpu7uaVca6grmUcSIIbS83AE6satL9Fm7m+SEKTIWVhOXmXp0fOo1jlQcrE2Vo50Z0/QP5G3eoW1qtWSMOBDgCCCCDpBB1hQDDOCzTykaTG65jd0bj0hDVuSpB59t1zvA+GpallTVWcy68XaLyPFNzWra1qGtW1rUNOctRzkjWrYGrJrVmGqIuUJcsQ1b6eeSPTG8t6yB1jakDVlmJGvLThNNDnGJRONRQpwiw9O3wi1/FtvNZdAxhf8Ww8CfSmeyLK6y15xooIp76HaQSq5loJ+QJ7GMZ+JHl/2WX6R/M/zB+SYkWT/AF1Pfm/tZ/FN9DgdXaeKff0j+ZPl/wBkfpJ8yfL/ALJisiyX15Pfmftb/FJ6JA6u08U+/pJ8yf4n9licZvmf5n/VMZCxLUvrye/M/a3+KcJOB1dp4p7ONHzH8z/qsHY17oP5n/VMbmrU5qcLZnT+J+1v8VIJKX6m08U8vxtk2QsHEuK4anGyqPgiNnS1lz9olNz2rnkapPWk04Y4h2DcArMOTlx+GN+9asI4SqJ/1sr3DXm51meSNHcmmZicZGrklapIUYuNXGp7ca1oJDRQCgzBNcrFyvanGZq43tW3LRFow3LkcEi2PCwW5BdUKwEKyclmCSOUq3j5qO44Fzh9kX6XKFYvYHlrJ2xRjWbvda7WtGsnt6yQrwwdRMp4mQxCzGNDW/mekm5PFWI0SjcEZUN8op8Q4Po7ek+/sb/e6q60IQqiCELlraNkzCyQXB0g7QdhHSupCa5ocKG4pQSDUXhQLCGDJKd1iLtOp4HNP5HoXM1qsKSMOBa4Ag6wRoTJV4vNOmF2b8l1y3qOsd6Fp6wng4UvjHVJx9xOIjSda2YFpNcKRMRz5P63aFH2tWYauuTBkzPCjNt40juWnN3objQokH/I0t0gjerYiB3RNdCwDUtlmAlsq+Em1WuyLLZZJZdVdVa7IssrIS1SpLJbJUBcuWNliQtqxIXArgVpcFpcF0uC0vCkaVI0rneFzyNXU8LQ8KZpVlpXFI1ckrV3yBckoV2E6iuQym+Zq4pWpykady2U+LtZMRydPJbxnN5JvlOsFtSrsK7GroiCGKvIAzk03pgeF2YEwHPWyhkLDsznm4Y0bydnDWVOcEZOtIdWS6PiojccHOI46AOtTihoooGCOBjY2DU1ot1neekohg4TRjWXPcoYMJuDL+07P8o47u1cGLuAYaGEMjGc51jJIRznG3RsGmw2X3kkvSEKStUGRIj4ry95qTeUIQhcmIQhC5chCELlyFzVvg9RQhPHQdoTmdIKPV2zguJKhAk//kK3YXRSJShCx3qVYpEITCuQlCEJhXLIJHIQkypFrctJSoUjVK1aHrnkSoVqGrDFzPW/Bf6wIQtqQ6YUsToFTvAPgdqdUIRc3ohCEz/lKEIQlUKEIQuXIQhC5cv/2Q=="
   height="100px"
   width="100px"
   />
</div>
        </div>
            <Container fluid >
                <Row className=''>
                    <Col sm={2}></Col>
                    <Col className="mt-3">
                        <div style={{
                            display: "flex",
                            justifyContent: "flex-end",
                        }}>
                            <Image
                                src="/img/phone.PNG"
                                alt="Phone"
                                width={350}
                                height={550}
                            />
                        </div>


                    </Col>
                    <Col className="mt-3">
                        <div style={{
                            // justifyContent: "flex-start",
                        }}>
                            <Card
                                style={{ width: "350px" }}
                            >
                                <Card.Title>
                                    <Link href="">
                                        <div style={{
                                            display: "flex",
                                            justifyContent: "center",
                                            alignItems: "center",
                                        }}>
                                            <Image
                                                src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRy57NIobf2Tszx0d2mNr7UwWcsUI71jgsp-Q&usqp=CAU"
                                                objectFit="contain"
                                                height={100}
                                                width={200}
                                                style={{
                                                    borderRadius: "1rem",
                                                    borderColor: '#fff',
                                                    borderWidth: '6px',
                                                    width: "50%",
                                                    height: "100px",
                                                    marginTop: "20px"
                                                }}
                                            />
                                        </div>

                                    </Link>

                                </Card.Title>


                                <Form>
                                    <Card.Body>
                                        <p>
                                            <input type="text" className='form-control' placeholder='Phone Number or UserName' name='username' {...register("username",{required:true})} />
                                        </p>
                                        <p>
                                            <input type="password" className='form-control' placeholder='Password' name='password' {...register("password",{required:true})} />
                                        </p>
                                        <p>
                                            <button type='submit' onClick={handleSubmit(onSubmit)} className='form-control btn btn-info'>Login</button>
                                        </p>
                                        <Row>
                                            <Col sm={5}><hr /></Col><Col> <p style={{ textAlign: "center", margin: "5px auto" }} >OR</p> </Col><Col sm={5}><hr /></Col>
                                        </Row>
                                        <Row className="m-3">
                                            <Link href="" style={{ textAlign: "center", textDecoration: "none", fontSize: "15px", marginRight: "10px", color: "#737573" }}>
                                                Forgot Password
                                            </Link>
                                        </Row>
                                    </Card.Body>
                                </Form>
                            </Card>
                            <Card style={{ width: "350px" }} className="mt-3">
                                <p style={{ textAlign: "center", paddingTop: "5px" }}>
                                    Dont have an account? <Link href="/signup" style={{ textDecoration: "none", fontSize: "15px", marginRight: "10px", color: "#00a1f5" }}>SignUp</Link>
                                </p>
                            </Card>
                            <Row className="mt-3">
                                <span style={{ position: "relative", left: "110px" }}>Get the app</span>
                                <Col>

                                    <Link href="">
                                        <Image
                                            src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAWkAAACLCAMAAACUXphBAAABMlBMVEX///8AAADr6+uOjo6vr69ChfQ0qFPqQzX7vAQ2Njb8/PyGhoaUlJTw8PAyZLhDh/hSUlLJycmAgIBZWVnT09MuLi6bm5snJyf39/fl5eWpqal4eHhycnJmZmZfX1/a2tpERERHR0e6uroPDw/Ozs7ExMS4uLg0NDQcHBwfHx80qUwpp1WioqILCwtDg/vpPTY8lqw8lLXhRj0xnU4zq0Dsugv/xATwdCXpOTdwd88GEggVRSIZUCcOLxctkkghaTQSORwldjoUOS0eYDApT5g6laMJHg8qhkI/WCBaq0nWnwBKOAGzhgMeFgCRbQPprwRuUgJlrEZWjKffR0OUbwMrIADCkgPrQCQ3KQF0dsvdpgOOTRSkLyUlCgnANywwDgtiHBaFJh5IFRE3JDYZBwZhHBbq6cttAAAMwUlEQVR4nO2d+YOjthXHBWYOc3TwxQA2xtjGR9fettl0203SbNI727TpkR7ZbrebNv3//4VKTwLEZQ8M9ni8+v4yY07po8fTk5AEQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQu+7ZKG76N6YlaneEtovfaEY9+DsbHTXVYTuItfVldqGHWLOXXMlCe3VdjXWXLc1rwd6Ybnd24fOwiNSu6VYizqgO5Y7eujEPzKNXMuvDtoRoKtr6OrVfbXlth463Y9Q+kapClq23PZDJ/sRauLqdkXS4UaYdB3pm2lF0lN3/NCJfpQauZ1qoNWWIpxHHZnuRq1GWhOka2mp6IL0UdQWpI8kQfpYEqSPpWZJf/TxJz9rJFndzTR0uzSFc6r+SFLmkZawqzefxrvnc2UbZ8pSwoU1oT/mfQv+rsL+g5pIk6Q//vSS6OW9E+Wx1pRN2kiT6M665MSpoBSHSJbMeJsTkQ7Zhuma/MLZG5K/a5Wd9UBqkPTLS6Znn9wvTS1MTRkOFQzWw6RVFJhEAwn/HctIw39mcOAIOdLMNAMNyWPTZBwHPkKd1kgLVWQM8G9cajLpSV/b50L6k8tEn352jySNEFLAGtdTXQLS3M61g0zuSAf+mshZxxtDZNNGLH4yOviPbcvIlc6J9LNLXp9/VDtJDgr5n2nStw7qxT8i0j3kxC8mPISi3oIxQiNMWtXA25wN6Z9//zKtX9RMkYdUk/9dkXQH+fH+BSkzGw0WZNvZkP7lDz/MoK7prjWKatsGLQnpxRRrAxXeXtI+0uL9OrmUjdorA7XOh/T3nv4qa9WXv6njrhnptmqD1hOWPgdqwTuQ7nKXkm8lAriL7PbqbEjf3ORRX37+68op6lJ8S8OAUSmE9GiI5cHeO5BOus8t1JeAtNRH4fZ8SF8UoX5W2V33VORF/wdIXVX001O2jSikfhoDDlQ0NM6H9MXTnK+uE/E5xBKpCKqKpHsQcLDdJAyhpuwi+4xsmqDOWzV219Va6IGNaLt5pSAcPFckjZmyOhE3gKZSRBqX37m0EYF0CeqK0TVucthzywqxl25BlGdtiCD22096NSVNTIu0MH0SrjDSnorOivTFTTHqahFfwEah+KTDIojuTBqM0q2MkteYpN+DaExijEQbOrLC3kC0EgHGBRBUSUTTapo0Rl3gqyu7a0+zrBatGAeWDrLApmeatYyPmlg0zlha2ow/+3aoW/pwQH9YFi2FVfTPA6lx0sXVIrjr+g30c1DzpMt8NdbLbdGZ74kOQLrMVxN3/dtj5+90dAjSpaiffPHjV787dg5PRQchXVItYtDX19df/v7YeTwNHYb0xdMf5VFT0NfPr/9w7EyehA5EGqPOOpAnX1wzPf/qj8fO5gnoUKQvbjKomUUzvYfu+mCkM6if/IkHfUd3PZuYI23Um8z2H3r6OhxpjPrDEoumLmSfuw6m0dQQfxE0l+PBeDzu7Sy7tTeO1UsmqPXwz3uk44CkuWoxD5qwfrWrIdNLz8BpblSMhq9mL3cdYabu7OhsMxmEMq9/30OSjqvFpDJM61Vpsmb58fN66cHV1MXXMga7jjAzd7ZpBwyZKdupf9+Dkma+OuejY6sucyCDaLSS4fhONBd4Wj+XvKqTZoOgTpo0oC4FfX39ujhRawrXXozaK2k18UIYPdbQ9Jo7kjbY/HpKh1j1aZMmqIt8dGTUhWmaURcdct2jHcS98r6f7kg6ekU2hsSQNw4nTvri6Z/LQV8/Lwz16MQ9LbWtpRUdWUd3JD2Mf8KU7+7Jk7558YOf7CBddKUx4m2qcVUmPSCAwlMnffPig6sdqL8quhI8rpv6WdqjyqRhlLB94qRvXvzl6qoc9fOvi/JJ0uMcrllYnTTxZuppkyYWfQWonxeSLgw9NuQue73y7ajVapnZrZNuqzXMtkpmHt6YvEJMk+61Wnr2MlnSizzpwdANrVElczgk6ZsXV0w/LUL9/PVfiy4EofSeVHdZA1Jd8Ma5YZG3zDdy2myGwLxt4ZgtTJFeskU37LSvypImKfJ50t0o3O+T9/RdHBAa8bArqYNv4wT5NB+y3yMGTVDnSX9d3BhHaN9DOuAb6nHwN+YmwMuxmVrxNpuc1edJt5KcG/yDkCGtk586RzpMboQUjNCgF6bqQbEWpPqAfXnMdVwxB5Lh/Ld/FGNcsfRH8ixeJP/L9EIZLj1ulNrIGtBSdqUHnrTO75C5hyMVT5OhUPh6k4R0mLqiS29iR2ULj0nRzPrD9U+nQGdRvy59FwADabinOc2KmA59dJ2NNaVWDNYH9SgZ+rTpw3/qKqaEjIUVLe/Fke7RfUpXd6Ir86SVYZeILTVDipORpuf5m2gZq0CawPHMUEia/KKn9VCks6D5anFnh2mWtJu6uz+jpqiCza6hHwrGLwGQOYxWCoAczOBAycU2WdJ9OGob70vaoPl+DygGRvq25US+RWE3Iosc2PRc0lNYXJ8fiPTNi79fZRX76i/LOee9R5Y0GI3a5vfqzHfE3hFQT9jeqLtET5MO4uLAHopATAYD50jTvq2kRhxHTnxBC9pM8PoJ9KOQ5ivDLOoyBx0pxQw7AD8SrXi8JFdYWwJVhkF3SI1rNWhlbqRtGmC6RiSQbGLRA515ltgzZ0j7bAcX5a00N/Sn1hiODOil4UZteuejkb75Jus6Yl9d7qB5ICiJVLczJnhG5/DEGkl0TGILdQ0UuBlfDkBdpgoFfERCukPPGC9YyOIP44l2wM+hxTvfxO9nYtIDhZ2jQk9fwHwGcV3gT4qH/x1kDFMJaIz6n/s4s7isyNORCkiB/p7ETqF+Uk14H8JF0STDPpg2Nw/MTJEmBWqNWLxohz3uRunYI1ZEOsgsEhZI9H3MAjeSMiXO6wCki10H0Zt/leHl80nSI+ebX2OyfQwVGUe6TanY6dIhMYcz81Cq3R3wpGfE7FnO5VbaCrMtF6aIdHbhqkCKHy2oLkoWT2qedFFlCHr77zK4acFyRUpuM0GsbrM2DXYbQO4590jcNrPpxFjTNt2PMhR6Uka7SUM168BJvTAi3SYJaMFF/dyJVM2Pn/6mhPO7khTkREPj7BsWCB0WNKNGkgLo/ZmBZ+EaljKK/XRynbSfpu0Pp2hM9U7S8DBERe1FpKGC9UvcDlXjcwJKfPS3FQb00tDXSm2jbZCowRGb78CgVgQ1UWy+BCZx2ywwodrKKdJQHbjRzgmfp52kbw2u+KYxaTgHQpCybqeGSZeAfnNHx8FEn+xOcp/2NIY/g/ooeuLBMjVmXA4L85YQti1ZkUV+CAojIQ1xu8zKf+DYnCnuJ81KGkIOFMD/0WK8Vu68KA+Nki6uDN/+Zx/arFhIEMKKwDMvpElkHWmI0cWJhyKBdT3AuVPvSVcHAcBw3hQuQsuKayMCedrpNpajw0C7/TTUF1DrsY4TuAR7U4Ts0hkejZIurAw/uLOD5tQvuHPkh6n1qJ2QlgeN4wY0IpCnIW2HGHAo63byp9H1+B4mGqw54ZSe4aTj6VLSGjutE3GjpJl1LEqz1Ogc26LK8NvqmIk2uRsnj2WqGFTWX9FOBV8yS6OevkaKdDou9hNj3BPlcX22UcuFiJZA+aSlJueNF/joig6aUxCm0uXzUaqS7JLjanDJFUAYR9GjeI1+J6SkYbQY7G9zC52HyVIsu0iTboJVjNoBRxWw/Qjt7FhvkHQedHUHzcu0ZJukTbUNJRPzmgvYYzsav4L+sE+2qvacP3q5MchGQ9kqlLQ373Qin+z57IxUaDbBR8zz7Y9pp9OhD5bm2HDJVTvERzIc0GWVi80TNbe+R85H13LQaa17nueNC59IE+/JvXddjT2vl/t8QYA3SrQKzLlROKP66+GB52XfPpJHxik8mKox0v9tyEE3rFXy2oqEJ6Ux2L0F3QK7XjQ3tw5T2ne8+e4wGaqm8SJpHAOKvPdtSiSKNHZ9DaQ50u8ac9CNCULvqB1ITNpY7zz+Hmpnel4Kjmhuvbw3DTrohkRbLpOttDIhMsn3WzUl0ri3d6610OQakP97e0IOGhS1XPr0La9xsCn6uzqmmZpd1/S7d+9Ow29E6qaSnhvz1Jig2RLsPOTc1+r1koagc8B0Ey/d333IuZOWVpov27Yt9w/5tZ9bTdPyowTTOnvSWAPTDB7+a2zvA+nTkCB9LFX/9oX4nks9Vf6ei/hGUU1V/kaR+O5WTVX/7pb4llwt1fiWnPg+Yi3V+D6i+OZnHdX65qf4jm111fuOrfg2c1XV/jaz+N54Bd3ve+NkPg9m/dAfp38kct1o8lE9ycpUbwntl75QjP0498AWuovui1lISEhISEhISEhISEhISEhISEhISEhISEhISEhISOjR6//MgZ8r7dDfygAAAABJRU5ErkJggg=="
                                            width={150}
                                            height={60}
                                        />
                                    </Link>
                                    <Link href="">

                                        <Image
                                            src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAXYAAACHCAMAAAA1OYJfAAAA0lBMVEUAAAD////yUCJ/ugAApO//uQDT09PFxcVKSkpTU1NwcHD6UyODwADp6en/vwAzSgCKLhPURh5HaABvowDnTCB5sQAAS251VQAAqfcAXokAkNGPaADfogAAmN7trACNjY2rq6vu7u68vLzc3NzOzs5hIA6AgIAuLi4dHR0+Pj5gYGCgoKCpqamXl5cSEhJ7e3snJydmZmZPT08XFxcrKys4ODhEREQ3EghVHAwcKQAsQQCELBPKQxxEYwBqmwAAKz8AQmFCMABnSwAAhcKFYQDPlgCmUdxXAAALTklEQVR4nO2de4OzqBXGZXerMa29d3vdFTHNzZjbzKT3y27b7/+VKnCAI4rOvHknmAzPHzMJIMoPPBwumigO8qAojpOgG4tjT6KgGysJ2H0oYPeigN2LAnYvCti9KGD3ooDdiwJ2LwrYvShg96KA3YsCdi8K2L0oYPeigN2LAnYvCti9KGD3ooDdiwJ2LwrYvShg96KA3YsCdi8K2L3o7rEfaT4Yv2IFIZMr4Sj2P/1xXH9u0v3lJ+P66+ClXGq2iBOaX95UgAZqNRB9JlzZm7K8gUax//SH4/pZk+7nPxrXLwbOk2dEqVi+/vpXTfpyIJ7nx9ji9RneRq/A/sWoJPYvR+XGPisIEnOmu9RrK6QkRNXSpdrb6fOmEodK50vTwD4XjXx32mzOB5q5sTeVY2OPthv5/7mJ7BzACKFDpfOlSWCfceq1/jp3dZJ70oNdaUN6sMfmXpiUJoGdW5j0FRf7duxlwO7EXjfA5q7zbzboSx9ZpWcH9kMr4MmY/5fLSzeXF+1HXc4r57mu1hSwN43d4WqcYm5+4pO81LLkvmCjI0rCynLbijRclyU/vGjCGr51WebRNlMVfBA5k8UW0h7LMt5HlN93lOew458yZ2O4VhPAnjYF3PbGMOXaCM/cODsYeylBmkiDvdJhDXZKyI6fSbT+Y2l7TdwRXYMPm4lciUr8HpoA9srl5C2acid5ztslN9CyQfOn3LB9B+wm0mDP5R3QhK0E9iojRclJrnkllVUuGrfk3mAvYrKoK46+SkhR1QkZsmnXaQLYE8eAp/G5yYx/WOri93AoldlYDdv2BntGuIt0FP4NkYZrp7oVfrTsfYX1ERe0HepzrtMEsJdmfESZlOjrCl3oGOD1eTIa+4gnQ4meRcA4VZ1z7InOB8xYc/RuiM2nawLYM4NdWWjeyE9mKiWHQc+12CGQoduLDxm4x7IyHUyhp8527zaJNgHspSkcQdibMrPNjOuSg6tzJfYYAjM8ewb31Arwy2NgvJY/MnZmmvXmctlcAHtCsETzvBI7hUCCx1CZhLwyWcca+/KRsdcWTMAet7CLirkSu7LTLcewlNMSHw/7S6v1CbYce+M+snSrlKqoz409kyk+HnbOBjnuCjvtTgB/Juy2bT9HHxL7nGDCCvuyO4r6TNhRZyKcST7A+oDYhRmn+htg54z1ZPCT+MuDNtaxreFSZ5mjF/sWWZkYavwjYhf+epYLaClTg1OmuT8xqtNx84DpauwRriYU28UuZh1kMD+HqNIPiV1NPRWF8duFDW7KzZJS3wucUrYonttHAnbucZYLSRHF9mAXORcJ4/hhkPQxsUe5GqBydsDxyfiQYBPW8lvPDGQkPSLb0Bjs7eW9hXZMYXkFYS8x9nda/J4K9qZjZWK+MKnRho0ty3izzDXnI81IxjDZmrKzimQ8spVpEwtcD4zhaa1U5qwdyTVj9Ekfs1WnH9mE88maDvYPpYDdiwJ2LwrYvShg96KA3YsCdi8K2L0oYPeigN2LAnYvuiX2wac57l3H585k/4BGsf/ti1+O6u9Nun98+atR/fO6kk1WZyZ3T7qfQrF1n0/qrVN7kcmn9NaSoYeorEMmgP1lqfTcn+Cg4mECmO/wKt9x9/mbtDYrBfeFfa6vm/bGn3S8nFmX+6+n8iiYecLwc2L/19fj+neT7rtfj+v7/lMY7O4N12ixbwVf3mkF4o2i5F2w//Y34/qmSff7H4/r2/5TGOy9+5qfSRv7dvDWuLHUxS1Ox9WBQuCps5Ru6xXYvxrV7yKO/Qej+kP/KRD2vqXLysIOa6bdbQI+VBPLh1kfErPJ1amJYe/udMHPx8COgsSZ9PYCA6i/S5tzd9i77w/AsRK76FNLh9dzY2UW5sV9Yu++lCHuYo+eLsdOOj8qLBtzp9g7z+xtSA/26cg27XeHvZTN2r4YaSx3Afs7Yc+g0VtbemWVHF6D/fky63muuk9Pm9nGZaYuadr/RptVX/Y2dtndj+4lmxB2KEJ7FLQUYYccYz8wSilrd75bmI0iJZVm6oUnovyZv33Nt5tRlXJTqd6irGy+Gwq5FMmy5SjNWaEi9Eay7a6qwH8s60qqlscXVJzc/UKiKWFn8B9L7kmNWthpJ92ywD2AGCym8nOqphZgBHlpP5uzaE2pMRyFOpm6lb1qGBUZ0+kusM/kxZ5RlAxiw9j3pVVchH2mJnRiBypzc62zVoTG/pLZx5TCENYPgh2aNp61ZkB7CPtLp7gIe6rCBPakkxRZn6IdrrCnPcfwlxg8DvaDoQYS38toCDuaeO3BrqfR4sgyIlrQ3vWcFmyyB+yb3mOKR8IOnap5jC5XXAawawsT16d0my/a2DXIUnXPvC7ybXqqtO3YmBpuTtaMflcnprGrVMVunqZLfbsw8d6UGHqKQv/WMnwXPwG8wOZyytjtGQ1Z5mgIO8SQUrkNz8zCLqbMTjsNtlApVTWI8x3aDXQPe9xVk1Z+k34lCiAtVCWA4DU1Q0S5poUdzLRyj7e6TG7sQAGXQaTS2HWTg+4UzemrKeSZju1M+EMK9NwscF/g+DvHDletHjJKNDcndmix3QUGhd14KgXOQwqMPY10pViDqGW3UlUPLlM+BvY5bnNHE+7EXnZZSqV2276QLhF4FopnVZsaQIIeuTU6BfsuV2QeAzsUQ1rY2jRXF3bg1jMHktpAakxLCWotUm+lbbJqIZZ3SPtemuMKehDsO3TZssziQS4XdoDbs9AEMcYog0FpT9ND4DlCbntsxqeXvltgj2+bB8EO69PccJ5QiVzYwfb2vEQytRu3bNhWn5mbVAeilSkXFvpca7GcoFvgQbDDdfPmu0BEXdh3ppYs6TkZpQyfRQlYH0y2wPSCrsx+P16BKvBRsOtO9YhDXdgB1VM307djN8MpHTQ3NwPSI2KHQqXQkM3ro4aw9+wQex32ZYvrHs8enPSV2e+rhRsCfX4A7BUUROKHQBf2yiCy1MEOtr2936DC+TZa7QqFnbfmIdueoM8PgF0aF3JAZXNjByPR83sFHezgbrcXiCAQB6nZBn4LXGyqXDA/TcWXh8Hemp1VvpwLO3Dp+RGIDva6r+X2Hl4aloVu+EaVrpXokbCrmRJcXucotcAMsDrY+2oIbLf1jk3kmC96sodTDk0O3NMStl0ugoZBTuzQpxYdF7KDXU3h4qEVnIl7i9gZKjX2g1X95lIGp8JGdyNPEbtZP9AwndiP6r4wNjttr6XavJAXDm1ZtM0dMuDo2YwCJRFSi4SQsY09MRU5pClif1LUzYW5J353KjGVM7z8xez8fxe7QkgSGXhQKxhimaPi7z9snUy4jWrsWsidBBflYrbf02qwq7uPX+ncvb9kith1p2omRwZWl9ACc1ZKsjy4B/u5m5JLdrKyo0wYS1SMPMhsri9Ks1SurYiN/WRSu95KP1nsgAyFfPJaamu25tBJaZB19hSoMZK9LUFIGxEbe4Sv5s6wQwtG3vjQzoF1Z0MFD+3D3t5tKaW8GBs71QfFnWMKs7umgz1H6e4Nu7z2vR3g2p60Iy0JC9CLPXq2GGZbRx54PiBvR7VGT90QNMFwDfZvxvWfJt1/vx3X//pPcSq48FrCngfgsixFElh8rsRn7BuvaGFI1qK6zvKIzuJ9mpikMfLH1zWy3JU1t1ajX56jrQmgTJyF4iDzkr8rdg7ci2ZLShmtT6/YfHo+VJTulqn93tq1iKjnfd7fyymnPO5Vz8Nu6+ZScjf0B8J+XwrYvShg96KA3YsCdi8K2L0oYPeigN2LAnYvCti9KGD3ooDdiwJ2LwrYvShg96KA3YsCdi8K2L0oYPeigN2LAnYvCti9KGD3ooDdiwJ2LwrYvYhjj5OgGyvm2INur/8DgyWWCaMVigAAAAAASUVORK5CYII="
                                            width={150}
                                            height={44}
                                            style={{
                                                borderRadius: "10px"
                                            }}
                                        />
                                    </Link>
                                </Col>
                            </Row>
                        </div>

                    </Col>
                    <Col sm={2}></Col>
                </Row>
                <Row style={{ marginTop: "50px" }} >
                    <Col style={{ textAlign: "center" }} >
                        <span> <Link href="https://about.meta.com/" style={{ textDecoration: "none", fontSize: "15px", marginRight: "10px", color: "#737573" }}>Meta</Link></span>
                        <span> <Link href="https://about.instagram.com/" style={{ textDecoration: "none", fontSize: "15px", marginRight: "10px", color: "#737573" }}>About</Link></span>
                        <span> <Link href="https://about.instagram.com/en_US/blog" style={{ textDecoration: "none", fontSize: "15px", marginRight: "10px", color: "#737573" }}> Blog</Link></span>
                        <span> <Link href="https://about.instagram.com/about-us/careers" style={{ textDecoration: "none", fontSize: "15px", marginRight: "10px", color: "#737573" }}>  Jobs</Link></span>
                        <span> <Link href="https://help.instagram.com/" style={{ textDecoration: "none", fontSize: "15px", marginRight: "10px", color: "#737573" }}>  Help</Link></span>
                        <span> <Link href="https://developers.facebook.com/docs/instagram" style={{ textDecoration: "none", fontSize: "15px", marginRight: "10px", color: "#737573" }}>  API</Link></span>
                        <span> <Link href="https://privacycenter.instagram.com/policy/?entry_point=ig_help_center_data_policy_redirect" style={{ textDecoration: "none", fontSize: "15px", marginRight: "10px", color: "#737573" }}>  Privacy</Link></span>
                        <span> <Link href="https://help.instagram.com/581066165581870/" style={{ textDecoration: "none", fontSize: "15px", marginRight: "10px", color: "#737573" }}>  Terms</Link></span>
                        <span> <Link href="https://www.instagram.com/explore/locations/" style={{ textDecoration: "none", fontSize: "15px", marginRight: "10px", color: "#737573" }}> Locations</Link></span>
                        <span> <Link href="https://www.instagram.com/web/lite/" style={{ textDecoration: "none", fontSize: "15px", marginRight: "10px", color: "#737573" }}> Instagram Lite</Link></span>
                        <span> <Link href="https://www.threads.net/login" style={{ textDecoration: "none", fontSize: "15px", marginRight: "10px", color: "#737573" }}> Threads</Link></span>
                        <span> <Link href="https://www.facebook.com/help/instagram/261704639352628" style={{ textDecoration: "none", fontSize: "15px", marginRight: "10px", color: "#737573" }}> Contact Uploading & Non-Users</Link></span>
                        <span> <Link href="https://about.meta.com/technologies/meta-verified/" style={{ textDecoration: "none", fontSize: "15px", marginRight: "10px", color: "#737573" }}> Meta Verified</Link></span>
                    </Col>
                </Row>
            </Container >
        </>
    )
}

export default Front